In [ ]:
import torch

Torch Tensors

In [ ]:
# 1-D Tensor
a = torch.tensor([2,2,1])
print(a)

In [ ]:
# 12-D Tensor
b = torch.tensor([[2,2,1],[3,4,5],[2,8,9],[1,7,2]])
print(b)

In [ ]:
# size and shape
print(a.shape)
print(b.shape)
print(a.size())
print(b.size())
# shape is attribute and size is a method

In [ ]:
# get height / number of rows
print(b.shape[0])

In [ ]:
# float tensor
c = torch.FloatTensor([[2,2,1],[3,4,5],[2,8,9],[1,7,2]])
print(c)
print(c.dtype)
# or we can also write c = torch.tensor([[2,2,1],[3,4,5],[2,8,9],[1,7,2]], dtype = torch.float)

In [ ]:
# double tensor
d = torch.DoubleTensor([[2,2,1],[3,4,5],[2,8,9],[1,7,2]])
print(d)
print(d.dtype)
# or we can also write c = torch.tensor([[2,2,1],[3,4,5],[2,8,9],[1,7,2]], dtype = torch.double)
# double is just higer precision float

In [ ]:
# mean
print(c.mean())
print(d.mean())

In [ ]:
# standard deviation
print(c.std())
print(d.std())

In [ ]:
# Reshape b
# Note: if one of the dimensions is -1, its size can be inferred

# view is used to reshape
print(b.view(-1,1)) # metion no. of columns, no. of rows not needed
print(b.view(12))   # 1-D array
print(b.view(-1,4))  
print(b.view(2,6)) 

# Assign b a new shape
b = b.view(1, -1)
print(b)
print(b.shape)


In [ ]:
# Create a 3D tensor with 2 channels, 3 rows and 4 columns (channels, rows, columns)
three_dim = torch.randn(2,3,4)
print('\n')
print(three_dim)
print(three_dim.view(2,12))
print(three_dim.view(2,-1))

In [ ]:
# Create a matrix with random numbers between 0 and 1
r = torch.rand(4,4)
print(r)

In [ ]:
# Create a matrix with random numbers taken from a normal distribution with mean 0 and variance 1
r2 = torch.randn(4,4)   # n stands for normal distribution
print(r2)
print(r2.dtype)

In [ ]:
# Create an array of 5 random integers from values between 6 and 9 (exclusive of 10)
in_array = torch.randint(6,10,(5,))   # int stands for integers
print(in_array)
print(in_array.dtype)

In [ ]:
# Create an 2-D array of size 3x3 from values between 6 and 9 (exclusive of 10)
in_array2 = torch.randint(6,10,(3,3))   # int stands for integers
print(in_array2)
print(in_array2.dtype)

In [ ]:
# Get number of elements in an array
print(torch.numel(in_array))
print(torch.numel(in_array2))

In [ ]:
# Create a 3x3 matrx of zeros and dtype=long
z = torch.zeros(3,3, dtype=torch.long) 
print(z)
print(z.dtype)

# Create a 3x3 matrx of zeros and dtype=long
o = torch.ones(3,3) 
print(o)
print(o.dtype)

In [ ]:
r2_like = torch.randn_like(r2, dtype = torch.double)
print(r2_like)

In [ ]:
# Add two tensors of same size amd datatype
add = torch.add(r,r2)
print(add)

In [ ]:
# In-place addition (change value of r2)
r2.add_(r)
print(r2)

In [ ]:
# Matrix Slicing
print(r2[:,1])      #All rows and 1st col
print(r2[:,:2])     #All rows and cols from 0th till 2nd
print(r2[:2,:])     #All cols and rows from 0th till 2nd
print(r2[:3,:])     #All cols and rows from 0th till 3rd

In [ ]:
# Extracting numbers
num_ten = r2[2,3]
print(num_ten)
print(num_ten.item())

NumPy Bridge

In [ ]:
import numpy as np

In [ ]:
# Convert a torch tensor to Numpy array
a = torch.ones(5)
print(a)
b = a.numpy()
print(b)

# Note: the value of b is dependent on a
a.add_(1)
print(a)
print(b)

In [ ]:
# Convert a Numpy array to torch tensor
a = np.ones(5)
print(a)
b = torch.from_numpy(a)
print(b)

# Note: the value of b is dependent on a
np.add(a, 1, out =a)
print(a)
print(b)

In [ ]:
# Move tensor to GPU
r2 = r2.cuda()
print(r2)

In [ ]:
# Switching between CPU and GPU
CUDA = torch.cuda.is_available()
print(CUDA)

if CUDA:
    add = add.cuda()
    print(add)

In [ ]:
# list to tensor
a = [2,3,4,5]
print(a)
to_list = torch.tensor(a)
print(to_list, to_list.dtype)

In [33]:
data = [[1.,2.],[3.,4.],
        [5.,6.],[7.,8.]]
T = torch.tensor(data)
print(T, T.dtype)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]]) torch.float32


Tensor Concatenation

In [38]:
#Tensor Concatenation
first_1 = torch.randn(2,5)
print(first_1)
second_1 = torch.randn(3,5)
print(second_1)
print('\n')

# alnog 0 dimension (rows)
con_1 = torch.cat([first_1,second_1])
print(con_1)
print('\n')
print('\n')

first_2 = torch.randn(2,3)
print(first_2)
second_2 = torch.randn(2,5)
print(second_2)
print('\n')

# alnog 1 dimension (rows)
con_2 = torch.cat([first_2,second_2], 1)
print(con_2)

tensor([[-0.0981, -0.0665,  0.8722, -1.5855, -1.1453],
        [-1.3275, -0.3363,  0.9044,  0.7964,  0.2623]])
tensor([[ 0.3732, -0.5219, -1.6085,  0.6982, -1.3337],
        [-0.2567, -1.4410, -0.5926, -0.1304, -0.4153],
        [ 1.0518, -0.8004,  0.1455,  0.1574, -0.1001]])


tensor([[-0.0981, -0.0665,  0.8722, -1.5855, -1.1453],
        [-1.3275, -0.3363,  0.9044,  0.7964,  0.2623],
        [ 0.3732, -0.5219, -1.6085,  0.6982, -1.3337],
        [-0.2567, -1.4410, -0.5926, -0.1304, -0.4153],
        [ 1.0518, -0.8004,  0.1455,  0.1574, -0.1001]])




tensor([[ 0.8274,  0.2075,  0.0774],
        [-0.2129,  0.9322, -1.6699]])
tensor([[ 1.6219, -1.3306,  0.9079, -0.0447, -1.8829],
        [ 0.6160,  2.5710, -1.5520, -0.2859, -1.9279]])


tensor([[ 0.8274,  0.2075,  0.0774,  1.6219, -1.3306,  0.9079, -0.0447, -1.8829],
        [-0.2129,  0.9322, -1.6699,  0.6160,  2.5710, -1.5520, -0.2859, -1.9279]])


Adding Dimensions to Tensor

In [40]:
#Adds a dimension of 1 along a specified index
tensor_1 = torch.tensor([1, 2, 3, 4])
tensor_a = torch.unsqueeze(tensor_1, 0)
print(tensor_a)
print(tensor_a.shape)
tensor_b = torch.unsqueeze(tensor_1,1)
print(tensor_b)
print(tensor_b.shape)
print('\n')
tensor_2 = torch.rand(2,3,4)
print(tensor_2)
print('\n')
tensor_c = tensor_2[:,:,2]
print(tensor_c)
print(tensor_c.shape)
print('\n')
tensor_d = torch.unsqueeze(tensor_c,2)
print(tensor_d)
print(tensor_d.shape)

tensor([[1, 2, 3, 4]])
torch.Size([1, 4])
tensor([[1],
        [2],
        [3],
        [4]])
torch.Size([4, 1])


tensor([[[0.0949, 0.8065, 0.5305, 0.0296],
         [0.3586, 0.1201, 0.3152, 0.6690],
         [0.6651, 0.4827, 0.1405, 0.3825]],

        [[0.4896, 0.7039, 0.5796, 0.1766],
         [0.7861, 0.4572, 0.5373, 0.9621],
         [0.3303, 0.9349, 0.6975, 0.9184]]])


tensor([[0.5305, 0.3152, 0.1405],
        [0.5796, 0.5373, 0.6975]])
torch.Size([2, 3])


tensor([[[0.5305],
         [0.3152],
         [0.1405]],

        [[0.5796],
         [0.5373],
         [0.6975]]])
torch.Size([2, 3, 1])
